services:
  gateway:
    build:
      context: ..
      dockerfile: v3/gateway/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - users
      - orders

  users:
    build:
      context: ./upstreams
    environment:
      SERVICE_NAME: users

  orders:
    build:
      context: ./upstreams
    environment:
      SERVICE_NAME: orders
